[package]
name = "guru"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[dependencies]
cairo-rs = "0.6.0"
gdk = "0.10.0"
gio = "0.6.0"
glib = "0.7.1"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_22_30"]
